{"name": "test_div[整数/0]", "status": "failed", "statusDetails": {"message": "AssertionError: assert None == 0\n  +None\n  -0", "trace": "self = <python_pratice.testing.test_calc.TestCalc object at 0x000002083B930BE0>\nget_calc = <python_pratice.Python_code.calc.Calculator object at 0x000002083B8F3A30>, get_div_datas = [3, 0, 0]\n\n    @pytest.mark.div\n    @pytest.mark.run(order=3)\n    @allure.story(\"测试除法\")\n    def test_div(self, get_calc, get_div_datas):\n        result = None\n        try:\n            result = get_calc.div(get_div_datas[0], get_div_datas[1])\n            if isinstance(result, float):\n                result = round(result, 2)\n        except Exception as e:\n            print(e)\n        print(f\"{get_div_datas[0]}/{get_div_datas[1]}={get_div_datas[2]}\")\n>       assert result == get_div_datas[2]\nE       assert None == 0\nE         +None\nE         -0\n\ntest_calc.py:47: AssertionError"}, "parameters": [{"name": "get_div_datas", "value": "[3, 0, 0]"}], "start": 1607359023183, "stop": 1607359023183, "uuid": "319739b6-9c72-43e2-a3de-e2f31d77a6a7", "historyId": "60289958225b24519d570c4e7ae1db05", "testCaseId": "4a57f615ae930c12d705a9fc7a66b88d", "fullName": "test_calc.TestCalc#test_div", "labels": [{"name": "story", "value": "测试除法"}, {"name": "feature", "value": "测试计算器"}, {"name": "tag", "value": "div"}, {"name": "tag", "value": "run(order=3)"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "LAPTOP-OS95OIT7"}, {"name": "thread", "value": "8396-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc"}]}